//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulePresenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentSchedule
    {
        public int ID { get; set; }
        public int GROUP_ID { get; set; }
        public int WEEK_ID { get; set; }
        public byte[] SCHEDULE_PNG { get; set; }
        public byte[] SCHEDULE_PDF { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Week Week { get; set; }
    }
}
