//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulePresenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTeacher
    {
        public int ID { get; set; }
        public int Department_ID { get; set; }
        public int Teacher_ID { get; set; }
        public int POSITION_DV_ID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
