//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulePresenter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDefinition
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string NAME_SHORT { get; set; }
        public double DURATION { get; set; }
        public int CLASSES_TYPE_DV_ID { get; set; }
        public int SEMESTER_TYPE_DV_ID { get; set; }
        public int MAJOR_ID { get; set; }
        public string YEAR_OF_STUDY { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public int ID_CREATED { get; set; }
        public Nullable<int> ID_MODIFIED { get; set; }
    
        public virtual Major Major { get; set; }
    }
}
